# Generated by Django 2.2.13 on 2020-08-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200815_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='mentions',
        ),
    ]
